security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 15

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
