services:
    manager.base:
        abstract: true
        calls:
            - [setNeoClient, [%database_schema%, %database_host%, %database_port%, %database_username%, %database_password%]]

    manager.interest:
        class: AppBundle\Service\InterestManager
        parent: manager.base

#    listener.cors:
#            class: AppBundle\Event\Listener\CORSListener
#            tags:
#                - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}
#                - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}