services:
    manager.base:
        abstract: true
        calls:
            - [setNeo4j, [%database_schema%, %database_host%, %database_port%, %database_username%, %database_password%]]
            - [setMailer, [@mailer]]
            - [setTemplateEngine, [@templating]]
            - [setContainer, [@service_container]]

    manager.interest:
        class: AppBundle\Service\InterestManager
        parent: manager.base

    manager.timeline:
        class: AppBundle\Service\TimelineManager
        parent: manager.base

    manager.access:
        class: AppBundle\Service\AccessManager
        parent: manager.base

    manager.user:
        class: AppBundle\Service\UserManager
        parent: manager.base

    manager.content:
        class: AppBundle\Service\ContentManager
        parent: manager.base

    formatter:
        class: AppBundle\Service\Formatter
        parent: manager.base

    listener.cors:
        class: AppBundle\Event\Listener\CORSListener
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}
            - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}

#    listener.exception:
#        class: AppBundle\Event\Listener\ExceptionListener
#        tags:
#            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException}